### ISSUE TITLE
类型一致性

### ISSUE THREAD

**Issue by shuqingzai** [chenmingyong0423/go-mongox#3]
在 Creator 中定义相关方法时，采用范型 T 作为文档数据，参考：https://github.com/chenmingyong0423/go-mongox/blob/099472caedc6f1ce1ccceed028df864ed0dd37c7/creator/creator.go#L27

但是在 Finder 中定义的相关方法却采用范型 *T 类型，导致创建与查询类型不一致，参考：https://github.com/chenmingyong0423/go-mongox/blob/099472caedc6f1ce1ccceed028df864ed0dd37c7/finder/finder.go#L26

这是有意为之吗？

一般的做法
1. 对单条数据操作时采用 *T 吧？
2. 批数据采用 []T 吧？slice 本来就是存储数组指针，返回 []*T 没有多大意义吧？

**Comment by chenmingyong0423** [comment]
> 在 Creator 中定义相关方法时，采用范型 T 作为文档数据，参考：
> 
> https://github.com/chenmingyong0423/go-mongox/blob/099472caedc6f1ce1ccceed028df864ed0dd37c7/creator/creator.go#L27
> 
> 但是在 Finder 中定义的相关方法却采用范型 *T 类型，导致创建与查询类型不一致，参考：
> 
> https://github.com/chenmingyong0423/go-mongox/blob/099472caedc6f1ce1ccceed028df864ed0dd37c7/finder/finder.go#L26
> 
> 这是有意为之吗？
> 
> 一般的做法
> 
> 1. 对单条数据操作时采用 *T 吧？
> 2. 批数据采用 []T 吧？slice 本来就是存储数组指针，返回 []*T 没有多大意义吧？

嗯，确实是要保持类型一致性，我对 `iCreator` 的更新计划是这样的：
```go
type iCreator[T any] interface {
	InsertOne(ctx context.Context, docs *T, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error)
	InsertMany(ctx context.Context, docs []*T, opts ...*options.InsertManyOptions) (*mongo.InsertManyResult, error)
}
```
`T` 都使用指针的形式，避免产生不必要的复制，影响性能。特别是处理较大数据结构的时候，MongoDB 本身也是文档型数据库，数据结构一般都比较复杂。也方便后续在提供的钩子函数里面修改数据。

对于 `iFinder` 接口，保持不变：
```go
type iFinder[T any] interface {
	FindOne(ctx context.Context, opts ...*options.FindOneOptions) (*T, error)
	Find(ctx context.Context, opts ...*options.FindOptions) ([]*T, error)
	Count(ctx context.Context, opts ...*options.CountOptions) (int64, error)
}
```

**Comment by chenmingyong0423** [comment]
This issue has been resolved by PR #4
