### ISSUE TITLE
提个想法

### ISSUE THREAD

**Issue by ghost** [chenmingyong0423/go-mongox#43]
比如说定义以下结构:
type User struct {
    Name         string `bson:"name"`
    Age          int    `bson:"age"`
}

查询的时候或者更新的时候, 像下面这样, 有可能会拼错"name" 
update.Set("name", "Mingyong Chen")

或者后期重构的时候, 也有可能漏改了部分的"name"
有没什么方式能从User结构里面直接获取名称, 你有这种困扰么?

另外一个想法, qmgo索引支持有点差, 比如全文索引创建和列出索引就没实现. 我感觉索引很重要, 不知道为啥他们不咋关心这

**Comment by 888go** [comment]
我出现过拼写错误, 导致往数据库里面插入新的字段. 关键还没及时发现, ....

**Comment by chenmingyong0423** [comment]
> 比如说定义以下结构: type User struct { Name string `bson:"name"` Age int `bson:"age"` }
> 
> 查询的时候或者更新的时候, 像下面这样, 有可能会拼错"name" update.Set("name", "Mingyong Chen")
> 
> 或者后期重构的时候, 也有可能漏改了部分的"name" 有没什么方式能从User结构里面直接获取名称, 你有这种困扰么?
> 
> 另外一个想法, qmgo索引支持有点差, 比如全文索引创建和列出索引就没实现. 我感觉索引很重要, 不知道为啥他们不咋关心这

**Comment by chenmingyong0423** [comment]
> 比如说定义以下结构: type User struct { Name string `bson:"name"` Age int `bson:"age"` }
> 
> 查询的时候或者更新的时候, 像下面这样, 有可能会拼错"name" update.Set("name", "Mingyong Chen")
> 
> 或者后期重构的时候, 也有可能漏改了部分的"name" 有没什么方式能从User结构里面直接获取名称, 你有这种困扰么?
> 
> 另外一个想法, qmgo索引支持有点差, 比如全文索引创建和列出索引就没实现. 我感觉索引很重要, 不知道为啥他们不咋关心这

这个问题嘛，其实你可以定义一个常量 UserNameField = "name"，或者直接将 `User` 的实例作为更新文档去更新记录（需要忽略零值字段）。通过 `User` 结构体去直接获取名称就需要通过反射去实现了，我觉得没有多大必要。

**Comment by chenmingyong0423** [comment]
> 另外一个想法, qmgo索引支持有点差, 比如全文索引创建和列出索引就没实现. 我感觉索引很重要, 不知道为啥他们不咋关心这

你的想法是什么呢，获取到 `mongo` 的 `Collection` 对象，就可以创建和查询索引了，你希望有更简易的操作吗？

**Comment by 888go** [comment]
> > 另外一个想法， qmgo索引支持有点差， 比如全文索引创建和列出索引就没实现.我感觉索引很重要, 不知道为啥他们不咋关心这
> 
> 你的想法是什么呢，获取到 的 对象，就可以创建和查询索引了，你希望有更简易的操作吗？`mongo``Collection`

嗯, 差不多这想法, 就是封装个索引的.

**Comment by 888go** [comment]
> > 比如说定义以下结构： type User struct { Name string Age int`bson:"name"``bson:"age"` }
> > 查询的时候或者更新的时候， 像下面这样， 有可能会拼错“name” update.Set（“name”， “陈明勇”）
> > 或者后期重构的时候， 也有可能漏改了部分的“name” 有没什么方式能从User结构里面直接获取名称， 你有这种困扰么？
> > 另外一个想法， qmgo索引支持有点差， 比如全文索引创建和列出索引就没实现.我感觉索引很重要, 不知道为啥他们不咋关心这
> 
> 这个问题嘛，其实你可以定义一个常量 UserNameField = “name”，或者直接将 的实例作为更新文档去更新记录（需要忽略零值字段）。通过 结构体去直接获取名称就需要通过反射去实现了，我觉得没有多大必要。`User``User`

也对, 也没啥好的办法. 将就用吧. 等有好主意再说.

**Comment by chenmingyong0423** [comment]
> > > 另外一个想法， qmgo索引支持有点差， 比如全文索引创建和列出索引就没实现.我感觉索引很重要, 不知道为啥他们不咋关心这
> > 
> > 
> > 你的想法是什么呢，获取到 的 对象，就可以创建和查询索引了，你希望有更简易的操作吗？`` mongo``Collection ``
> 
> 嗯, 差不多这想法, 就是封装个索引的.

了解
