### ISSUE TITLE
Does it support transactions? I can't find that in the docs

### ISSUE THREAD

**Issue by ginlink** [chenmingyong0423/go-mongox#44]
在提交之前请先查找 [已有 issues](https://github.com/chenmingyong0423/go-mongox/issues)，避免重复上报。| Before submitting, please search for [existing issues](https://github.com/chenmingyong0423/go-mongox/issues) to avoid duplicate reports.

### 您使用的 mongox 版本 | The version of mongox you are using
x
### 你的问题 | Your question
- Does it support transactions? I can't find that in the docs

### 你设置的的 Go 环境 | Your Go Environment Setting
> 上传 `go env` 的结果 | Upload the result of `go env`

**Comment by chenmingyong0423** [comment]
Currently, go mongox provides simple operation functions and methods for Collection. As we know, transaction operations in MongoDB are based on the mongo.Client instance, and go mongox does not yet include functions to encapsulate transaction operations. Therefore, at this time, transactions are not supported in go mongox. If you have any good ideas or designs, I would love to discuss them with you.

**Comment by chenmingyong0423** [comment]
Even if mongox doesn't provide easy handling of transactions, you can still use mongo.Client to start a transaction and then use the generic Collection provided by mongox to handle the data.

**Comment by ginlink** [comment]
> Even if mongox doesn't provide easy handling of transactions, you can still use mongo.Client to start a transaction and then use the generic Collection provided by mongox to handle the data.即使 mongox 不提供简单的事务处理，您仍然可以使用 mongo.Client 启动事务，然后使用 mongox 提供的通用 Collection 来处理数据。

I got that. Thank you for your reply.
