### ISSUE TITLE
[功能请求] | validator  这个包本身是支持多语言提示的, 建议加上这个功能

### ISSUE THREAD

**Issue by nuan1989** [chenmingyong0423/go-mongox#60]
validator  这个包本身是支持多语言提示的, 建议加上这个功能
初始化的时候, 传入需要提示的语言名称

要不报错了还得自己拦截再翻译.

**Comment by chenmingyong0423** [comment]
https://go-mongox.dev/plugins/plugins.html

mongox 提供了一个初始化的函数，你可以传入一个自定义的 validator 对象，这样是不是可以解决你所说的这个问题。

```go



validate := validator.New()
validate.RegisterTranslation(...)

mongox.InitPlugin(&mongox.PluginConfig{
EnableDefaultFieldHook: true,
EnableModelHook:        true,
EnableValidationHook:   true,
// 覆盖默认的校验器，当 EnableValidationHook 为 true 时生效
Validate: validate,
})
```

**Comment by nuan1989** [comment]
> https://go-mongox.dev/plugins/plugins.html
> 
> mongox 提供了一个初始化的函数，你可以传入一个自定义的 validator 对象，这样是不是可以解决你所说的这个问题。
> 
> ```go
> validate := validator.New()
> validate.RegisterTranslation(...)
> 
> mongox.InitPlugin(&mongox.PluginConfig{
> EnableDefaultFieldHook: true,
> EnableModelHook:        true,
> EnableValidationHook:   true,
> // 覆盖默认的校验器，当 EnableValidationHook 为 true 时生效
> Validate: validate,
> })
> ```

好吧...  就是用自己的库效验

**Comment by chenmingyong0423** [comment]
> > https://go-mongox.dev/plugins/plugins.html
> > mongox 提供了一个初始化的函数，你可以传入一个自定义的 validator 对象，这样是不是可以解决你所说的这个问题。
> > ```go
> > validate := validator.New()
> > validate.RegisterTranslation(...)
> > 
> > mongox.InitPlugin(&mongox.PluginConfig{
> > EnableDefaultFieldHook: true,
> > EnableModelHook:        true,
> > EnableValidationHook:   true,
> > // 覆盖默认的校验器，当 EnableValidationHook 为 true 时生效
> > Validate: validate,
> > })
> > ```
> 
> 好吧... 就是用自己的库效验

嗯嗯，`mongox` 默认使用 `validator.New()` 创建一个新实例，如果你有自己的扩展配置，你可以传入你的 `validator` 实例，`mongox` 支持注入新实例的，不会卡的那么死，可扩展。

**Comment by nuan1989** [comment]
> > > https://go-mongox.dev/plugins/plugins.html
> > > mongox 提供了一个初始化的函数，你可以传入一个自定义的 validator 对象，这样是不是可以解决你所说的这个问题。
> > > ```go
> > > validate := validator.New()
> > > validate.RegisterTranslation(...)
> > > 
> > > mongox.InitPlugin(&mongox.PluginConfig{
> > > EnableDefaultFieldHook: true,
> > > EnableModelHook:        true,
> > > EnableValidationHook:   true,
> > > // 覆盖默认的校验器，当 EnableValidationHook 为 true 时生效
> > > Validate: validate,
> > > })
> > > ```
> > 
> > 
> > 好吧...就是用自己的库效验
> 
> 嗯嗯， 默认使用 创建一个新实例，如果你有自己的扩展配置，你可以传入你的 实例， 支持注入新实例的，不会卡的那么死，可扩展。`mongox``validator.New()``validator``mongox`

倒是能满足需要, 实在不行就自己复制一份改改, 我看qmgo也是这样, 我倒是好奇平常你咋用的, 难道大家开发的网站都是面向国外? 或者说也是像我一样, 把错误拦截下来. 重新翻译后再输出.

**Comment by chenmingyong0423** [comment]
我没有用过 validator  的多语言功能，就是用的默认英文，你是怎么用的，可以贴代码出来看看。

**Comment by chenmingyong0423** [comment]
因为 `mongox` 本身是不涉及到扩展 `validator` 的功能的，只是你传入了什么实例，我就用什么实例。

如果你是想 `mongox` 针对 `validator` 的错误去做二次处理，那是不行的。

**Comment by nuan1989** [comment]
> 我没有用过 validator 的多语言功能，就是用的默认英文，你是怎么用的，可以贴代码出来看看。我看看能不能提供什么意见，或者我这边能不能扩展一下。


`package main

import (
	"fmt"
	"github.com/go-playground/locales/en"
	"github.com/go-playground/locales/zh"
	"github.com/go-playground/universal-translator"
	"github.com/go-playground/validator/v10"
	zh_translations "github.com/go-playground/validator/v10/translations/zh"
)

// User 结构体
type User struct {
	Name  string `validate:"required"`
	Email string `validate:"required,email"`
}

func main() {
	// 初始化验证器
	validate := validator.New()

	// 加载语言包
	en := en.New()
	zh := zh.New()

	// 创建通用翻译器
	uni := ut.New(en, en, zh)
	// 设置默认语言
	trans, _ := uni.GetTranslator("zh") // 默认为中文
	// 注册翻译器
	_ = zh_translations.RegisterDefaultTranslations(validate, trans)

	// 创建用户实例
	user := User{
		Name:  "",
		Email: "invalid-email",
	}

	// 切换语言为中文
	trans, _ = uni.GetTranslator("zh")

	// 进行验证
	err := validate.Struct(user)
	if err != nil {
		for _, err := range err.(validator.ValidationErrors) {
			// 获取多语言错误信息
			translatedErr := err.Translate(trans)
			fmt.Println(translatedErr)
		}
	}
}
`

-----------
以上输出:
Name为必填字段
Email必须是一个有效的邮箱

**Comment by nuan1989** [comment]
> 因为 `mongox` 本身是不涉及到扩展 `validator` 的功能的，只是你传入了什么实例，我就用什么实例。
> 
> 如果你是想 `mongox` 针对 `validator` 的错误去做二次处理，那是不行的。

我觉得初始化的时候, 加一个参数, 让用户自己选择输出的提示是中文还是英文, 会更加人性化点. 
这是validator本身自带的语言包, 只是国内大家好像了解的少. 也不算什么二次开发.

这只是建议,  对我使用没啥影响, 我可以复制一份自己改.

**Comment by chenmingyong0423** [comment]
> > 因为 `mongox` 本身是不涉及到扩展 `validator` 的功能的，只是你传入了什么实例，我就用什么实例。
> > 如果你是想 `mongox` 针对 `validator` 的错误去做二次处理，那是不行的。
> 
> 我觉得初始化的时候, 加一个参数, 让用户自己选择输出的提示是中文还是英文, 会更加人性化点. 这是validator本身自带的语言包, 只是国内大家好像了解的少. 也不算什么二次开发.
> 
> 这只是建议, 对我使用没啥影响, 我可以复制一份自己改.

如果加了这个参数，你目前的代码会怎么调整，我想知道。

**Comment by nuan1989** [comment]
> > > 因为 `mongox` 本身是不涉及到扩展 `validator` 的功能的，只是你传入了什么实例，我就用什么实例。
> > > 如果你是想 `mongox` 针对 `validator` 的错误去做二次处理，那是不行的。
> > 
> > 
> > 我觉得初始化的时候, 加一个参数, 让用户自己选择输出的提示是中文还是英文, 会更加人性化点. 这是validator本身自带的语言包, 只是国内大家好像了解的少. 也不算什么二次开发.
> > 这只是建议, 对我使用没啥影响, 我可以复制一份自己改.
> 
> 如果加了这个参数，你目前的代码会怎么调整，我想知道。

我没啥更好的建议, 我自己用的话就随便搞, 你这得为用户考虑. 
我觉得可以V2版本, 或者V3版本的时候加?

**Comment by chenmingyong0423** [comment]
其实我还没 get 到你的设计，你给出对比代码是最好的，这样我就能清晰你的想法了，例如

- 使用目前的 `mongox` 版本，你的翻译逻辑是怎么处理的
- `mongox` 升级，`mongox` 应该接收你传入的什么参数，它该怎么配置
- 升级后，你的翻译逻辑又是怎么样的。

**Comment by nuan1989** [comment]
> 其实我还没 get 到你的设计，你给出对比代码是最好的，这样我就能清晰你的想法了，例如
> 
> * 使用目前的 `mongox` 版本，你的翻译逻辑是怎么处理的
> * `mongox` 升级，`mongox` 应该接收你传入的什么参数，它该怎么配置
> * 升级后，你的翻译逻辑又是怎么样的。

那就算了, 我技术不咋地好, 就不卖弄了, 我只是想说validator 本身支持多语言. 建议集成下.

**Comment by chenmingyong0423** [comment]
哈哈没事。不过 `mongox` 本身是扩展 `mongo` 官网库，对于其他的依赖库，是不会做任何处理的。支持 `validator` 校验，并不意味着要对它扩展。

其实你传入你自己创建的 `validate` 对象给 `mongox`，就可以支持多语言了，大体步骤：
- 传给 `mongox` 之前，你要执行 `h_translations.RegisterDefaultTranslations(validate, trans)` 这个方法
- 之后通过 `mongox.InitPlugin` 函数传给 `mongox`

只不过最后你也得执行 `translatedErr := err.Translate(trans)` 这个逻辑去翻译，这是不可避免的，翻译的那些配置都得你自己去写的，`mongox` 不会加上这些逻辑，会破坏单一职责。

**Comment by chenmingyong0423** [comment]
`gin` 框架也集成了 `validator` 校验，也不会扩展它，只是提供某种方式让你替换它，思想都是一样的。

**Comment by nuan1989** [comment]
> `gin` 框架也集成了 `validator` 校验，也不会扩展它，只是提供某种方式让你替换它，思想都是一样的。

好吧, 虽然不是很赞同这种, 但是理解你的决定. 哈哈...

**Comment by chenmingyong0423** [comment]
> > `gin` 框架也集成了 `validator` 校验，也不会扩展它，只是提供某种方式让你替换它，思想都是一样的。
> 
> 好吧, 虽然不是很赞同这种, 但是理解你的决定. 哈哈...

其实就是遵循高内聚低耦合的设计原则，如果耦合了 `validator` 的一些逻辑在里面，后面 `validator` 出了 `bug` 之类的，那 `mongox` 也得跟着升级，难以维护。如果你让我加上 `mongo` 库的一些参数，那是完全可以的，因为 `mongox` 本身就是为了扩展 `mongo` 而开发的。

**Comment by chenmingyong0423** [comment]
我并没有说你的想法是错的，只是 `mongox` 不需要支持这种功能。你这种需求，去找对 `validator` 库进行封装的库，他们肯定支持。O(∩_∩)O
