### ISSUE TITLE
 undefined: options.DeleteOptions && undefined: options.UpdateOptions 

### ISSUE THREAD

**Issue by landaiqing** [chenmingyong0423/go-mongox#65]
在提交之前请先查找 [已有 issues](https://github.com/chenmingyong0423/go-mongox/issues)，避免重复上报。| Before submitting, please search for [existing issues](https://github.com/chenmingyong0423/go-mongox/issues) to avoid duplicate reports.

并且确保自己已经 | Also, ensure that you have:
- [x] 阅读过文档 | Read the documentation
- [x] 阅读过注释 | Reviewed the comments
- [x] 阅读过例子 | Looked at the examples

### 您使用的 mongox 版本 | The version of mongox you are using

``` go
github.com/chenmingyong0423/go-mongox/v2 v2.0.0-beta1
```

### 您遇到的问题 | The issue you encountered.

``` go

# github.com/chenmingyong0423/go-mongox/v2/deleter
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\deleter\deleter.go:29:64: undefined: options.DeleteOptions
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\deleter\deleter.go:30:65: undefined: options.DeleteOptions
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\deleter\deleter.go:96:84: undefined: options.DeleteOptions
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\deleter\deleter.go:116:85: undefined: options.DeleteOptions
# github.com/chenmingyong0423/go-mongox/v2/updater
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\updater\updater.go:34:64: undefined: options.UpdateOptions
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\updater\updater.go:35:65: undefined: options.UpdateOptions
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\updater\updater.go:36:61: undefined: options.UpdateOptions
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\updater\updater.go:115:84: undefined: options.UpdateOptions
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\updater\updater.go:139:85: undefined: options.UpdateOptions
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\updater\updater.go:163:81: undefined: options.UpdateOptions
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\updater\updater.go:165:31: undefined: options.Update
D:\GoPath\pkg\mod\github.com\chenmingyong0423\go-mongox\v2@v2.0.0-beta1\updater\updater.go:168:48: undefined: options.UpdateOptions
```

### 复现步骤 | Steps to reproduce
> 请提供简单的复现代码 | Please provide simple code to reproduce the issue. 

更新mongo-driver/v2
``` go
go: upgraded go.mongodb.org/mongo-driver/v2 v2.0.0-beta2 => v2.0.0
```

### 错误日志或者截图 | Error logs or Screenshots
![image](https://github.com/user-attachments/assets/a19213f5-02fa-45f1-af83-64e873236a9d)

### 你排查的结果，或者你觉得可行的修复方案 | Your Findings or Possible Solutions
> 可选。我们希望你能够尽量先排查问题，帮助我们减轻维护负担。这对于你个人能力提升同样是有帮助的。| Optional. We hope you can try to troubleshoot the issue first, helping us to reduce our maintenance burden. This is also beneficial for your personal skill development

更新go-mongox 支持的mongo-driver/v2 版本

### 你设置的的 Go 环境 | Your Go Environment Setting
> 上传 `go env` 的结果 | Upload the result of `go env`

**Comment by chenmingyong0423** [comment]
你是在 `go-mongox` 里面升级 `mongo-driver/v2` 依赖遇到的问题吗，我看了下，`mongo-driver` 还没有发布正式的 `v2.0.0` 版本，只是打了一个 `v2.0.0` 的 `tag`，等正式发布 `release` 的时候再同步更新下。

这个报错问题，我看了代码，`mongo-driver` 继 `2.0.0-beta2` 版本后又做了更新，将 `DeleteOptions` 和 `UpdateOptions` 拆分开了，拆分成 `DeleteOneOptions` 和 `DeleteManyOptions`，`UpdateOptions` 同理，后面升级又得调整这部分代码，害。

**Comment by chenmingyong0423** [comment]
你加上了 `bug` 标签，不过这实际上不算是 `bug`，所以你的需求是希望我能升级 `mongo-driver v2.0.0-beta2` 到  `mongo-driver v2.0.0` 对吧。

**Comment by landaiqing** [comment]
是的，麻烦更新一下，感谢 :pray: ！
这个bug 标签在提issue 的时候没太注意，抱歉 :flushed: ，下次注意！

> 你加上了 `bug` 标签，不过这实际上不算是 `bug`，所以你的需求是希望我能升级 `mongo-driver v2.0.0-beta2` 到 `mongo-driver v2.0.0` 对吧。

**Comment by chenmingyong0423** [comment]
@landaiqing 已发布 v2.0.0 版本：https://github.com/chenmingyong0423/go-mongox/releases/tag/v2.0.0
